apiVersion: apps/v1
kind: Deployment
metadata:
  name: fern-reporter
  labels:
    app: fern-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fern-reporter
  template:
    metadata:
      labels:
        app: fern-reporter
    spec:
      containers:
      - name: fern-reporter
        # Image is built locally via Tilt (no registry push)
        image: fern-reporter:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: FERN_HOST
          value: "postgres"
        - name: FERN_PORT
          value: "5432"
        - name: FERN_USERNAME
          value: "fern"         # <-- set to your actual DB username
        - name: FERN_PASSWORD
          value: "fern"         # <-- set to your actual DB password
        - name: FERN_DATABASE
          value: "fern"         # <-- set to your actual DB name
          # # Connect to the Postgres service in-cluster
          # value: "postgres://fern:fern@postgres:5432/fern?sslmode=disable"
